[workspace]
channels = ["conda-forge"]
name = "MANTEL_code"
platforms = ["osx-arm64","osx-64","win-64","linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
biopython = ">=1.85,<2"
freesasa = ">=2.2.1,<3"
matplotlib = ">=3.10.6,<4"
